"""Generate a .env file — or ENV.md docs — from scripts/env_schema.py.

    python3 -m scripts.generate_env                # show options (this help)
    python3 -m scripts.generate_env dev             # developer .env: most fields, terse comments
    python3 -m scripts.generate_env prod            # production .env: required + prod-relevant fields only
    python3 -m scripts.generate_env full             # every field, all commented, section-wise (reference dump)
    python3 -m scripts.generate_env docs            # (re)writes ENV.md from the same schema

    python3 -m scripts.generate_env dev --force      # overwrite an existing output file
    python3 -m scripts.generate_env prod --out .env.prod

Stdlib only, no third-party dependencies — run with plain `python3`, no venv
or `uv run` needed. `scripts/env_schema.py` is the single source of truth for
every field; this file only formats it.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

from scripts.env_schema import SECTIONS, Field

REPO_ROOT = Path(__file__).resolve().parent.parent


def _wrap_comment(text: str, width: int = 78) -> list[str]:
    return [f"# {line}" for line in textwrap.wrap(text, width=width)] or ["#"]


def _field_lines(f: Field, *, full: bool) -> list[str]:
    lines: list[str] = []
    note = f.description
    if f.required:
        note += "  [required]"
    lines.extend(_wrap_comment(note))
    if full and f.context:
        lines.extend(_wrap_comment(f.context))

    value = f.example or f.default or ""
    if f.required and not full:
        # Active line — the user must fill this in.
        lines.append(f"{f.key}={value}")
    else:
        lines.append(f"# {f.key}={value}")
    return lines


def _render_env(mode: str) -> str:
    full = mode == "full"
    out: list[str] = [
        "# Generated by `python3 -m scripts.generate_env "
        f"{mode}` from scripts/env_schema.py — do not hand-edit field comments,",
        "# change the schema and regenerate instead.",
    ]
    if mode == "dev":
        out.append(
            "# Developer .env — most settings, one-line comments. Fill in the required values below."
        )
    elif mode == "prod":
        out.append(
            "# Production .env — required fields + settings you should review before a real deploy."
        )
        out.append(
            "# Optional fields are commented under their section; uncomment and set what you need."
        )
    else:
        out.append(
            "# Full reference — every field this project reads, all commented, grouped by section."
        )
        out.append(
            "# cp this to .env and uncomment what you need (see ENV.md for the full explanation of each)."
        )
    out.append("")

    for section in SECTIONS:
        if full:
            fields = section.fields
        else:
            fields = tuple(
                f for f in section.fields if (f.in_dev if mode == "dev" else f.in_prod)
            )
        if not fields:
            continue
        out.append(f"# {'-' * 77}")
        out.append(f"# {section.title}")
        out.append(f"# {'-' * 77}")
        for f in fields:
            out.extend(_field_lines(f, full=full))
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def _render_docs() -> str:
    out: list[str] = [
        "# Environment variables",
        "",
        "Every env var this project reads, generated from `scripts/env_schema.py` — "
        "that file is the source of truth; edit it, then run "
        "`python3 -m scripts.generate_env docs` to refresh this page.",
        "",
        "Don't hand-write a `.env` from scratch. Instead:",
        "",
        "```bash",
        "python3 -m scripts.generate_env dev    # local development",
        "python3 -m scripts.generate_env prod   # production deploy",
        "python3 -m scripts.generate_env full   # every field, all commented (reference)",
        "```",
        "",
        "**Tags**",
        "",
        "- **required** — a normal install will not work without this being set.",
        "- **server** — `ServerSettings`: env/.env only, read once at process start; changing one needs a restart.",
        "- **user** — `UserSettings`: hot-reloads with no restart; also editable per-user from the settings UI, "
        "which takes precedence over the value set here.",
        "- fields with neither tag are bare names (not read through the `KRUTRIM_AGENT_` prefix) — "
        "provider SDKs, Vite, docker-compose, or Redis/Langfuse's own conventions.",
        "",
    ]

    for section in SECTIONS:
        out.append(f"## {section.title}")
        out.append("")
        out.append("| Variable | Required | Tier | Default | Description |")
        out.append("| --- | --- | --- | --- | --- |")
        for f in section.fields:
            desc = f.description
            if f.context:
                desc += f" {f.context}"
            desc = desc.replace("|", "\\|")
            out.append(
                f"| `{f.key}` | {'yes' if f.required else ''} | {f.tier or ''} | "
                f"{f'`{f.default}`' if f.default else ''} | {desc} |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python3 -m scripts.generate_env",
        description="Generate .env (dev/prod/full) or ENV.md from scripts/env_schema.py.",
    )
    parser.add_argument(
        "mode",
        nargs="?",
        choices=["dev", "prod", "full", "docs"],
        default=None,
        help="dev | prod | full write a .env; docs (re)writes ENV.md",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output file if it already exists",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: <repo root>/.env, or ENV.md for `docs`)",
    )
    args = parser.parse_args(argv)

    if args.mode is None:
        parser.print_help()
        return 0

    if args.mode == "docs":
        out_path = args.out or (REPO_ROOT / "ENV.md")
        content = _render_docs()
    else:
        out_path = args.out or (REPO_ROOT / ".env")
        content = _render_env(args.mode)

    if out_path.exists() and not args.force:
        print(
            f"error: {out_path} already exists — pass --force to overwrite it.",
            file=sys.stderr,
        )
        return 1

    out_path.write_text(content)
    print(
        f"wrote {out_path.relative_to(REPO_ROOT) if out_path.is_relative_to(REPO_ROOT) else out_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
